apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:jFD9i9WsRl5hgAEr5p6zforegA==,iv:SQz3NnpiJsr/B20UPz6704bCbS78JYoQkllTCeZG3iU=,tag:MoW05ICcG2BBqoXx9x+AVA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHozQ3NVTWdo
        elQrYWFXRUxSTFl2Q2Y4N2lRS0F3RmU5VnE2dTZtL3lLc3VFM011aFR6dW05c2Fk
        bVBGaXVManV1cGVMYnA1VHNWV1V3RVpIQzRQUTdQWjhhcXZsa25KbHVsaFdpODU4
        OW4rc3RUZXRKRHNnUS8xRkNaeUN6VUNZU1JCT2pJZDhMWjRvZHJYd211c21qa2ZU
        bCtiL05HcFd3b1VLditBZE5vemNZTVBMckZsTlk1TUQwcm02emYwNnpYVTFhaDZE
        Qm5tejR4ei9jTERvdVlpeFRXaEVaamh2Y2xpeit1bERzK2VQa2FaaHN2Y2tnT0JM
        c2pmMnNFTzBINTZzUnlyR2FFMDlVbThDL2I0b3RLZ2hzVnZMMlJBWkhXOTZ0TzlH
        SzF6SjZvT2ZaYTMxcTkzSTBJRGxkMmtqM0t3SHNIN1A2aDdXV1l2OWVZdWNLbmo3
        QU1NT3lKYVpTbERka3E3NWhFcVZ3cUQ3SHFYREtSc3FJa0ZPbDBadVk0SmpzMTE5
        dUZ5c25JeWJJMktpYVY2RjdsdlBMYllGL0ZWQjhPMTFpS2NRZEJGS1hqUnhqTmJ3
        d2YyakFGRldRUmU1SllXaVhQSWFHMWgvMVg0WWRFSndtVmFhMEtaMnN1bWhBNDN5
        ajJOR250TlJsMTVKOGNBQXBRaUkrWk9ZUml3MllWV3NXK0Y0NmJ2dHIyWmJTbFpn
        OTRGNWxtUlVaenFUVTVaZktHclVWeEk0dHh0dDY0dmQ3RFY5SjdrQ0YzVkxIK3U4
        ZnZab0M5VGM5TTRvQWNxVnVjZU9aT0ZYTEJhUmxVUlhEL21TVndnVktUSk1lQllY
        SWdZL2liZ0k3NU0rK0kzd1N2TklvVW9OdWhwMG9aeGJ5bVRROVF5b08xUGY1Q2lJ
        QUFkVjc2MzlRcFloaW1ZUWRCK2daNXo3TUtIdnNBNHM1UzJ1YWhBZDNGTlFkdTBk
        RktqUkVOL1pOWFdCZnRNQXRrTlFFVVQwc3JBL0R5dFBNbjFKcHpSdjI2QVBXTVR6
        bm0vTm4rK2JiQ09uQUNpQkRLV3IvRDF1dUQ1M1Uwcmd2VkxRMVNPRFdJaGdRUTRv
        MHdTdmhaT01OSHJ0WVlyREtwdXBnVTVvZVhUeUtQU1AwbVpoNmJyZTRTT1Z1aXVX
        anRaeFd0L24xS3N2UUR1VWIvMEFKdEROaFJhci9hemRDbnlRY1NtNU8xMWNFejEz
        a0dqSjhmVmt3TzBvN3hDMFo1YVluMnVaTDJzL0x2OWthcEhsWW9SbWo0djd6clpm
        UDhhTEd2dFZuc0ovYjN1ekRVcWhCeitDRzRPTzIwekJJZ2pQU1hPN0xwYnltaDZK
        Z252ZW10c2xjcjZKNUJGZ0EyeHh2SXB2WVFYNWJacjNEYW9RT0Z3bk9vWjV1VUNH
        SFpiVVo4bHI4LzBMSDd5SzBCNUROTHhZa2lmUG8yWkgvOEhmMEplR3ZHY1BLL3B2
        a01TdTVOR0t0MjNUSStjcXJldGxKYnV3d1BtYXhXYkNnaDFNbkl1WVh1MEVSMlpi
        R0RXeFZFM3g5STA4U243aGlHMDArNE1XZmk5MmRRYkpWWjdyS25pb0NiaS9CK3hn
        ZVJQVW5MWnJENVpPVGR3L2o5RHVFMnJsTHpsU20yTmZ6Sk8yMzdwR3haLzVyOXBr
        WmVacVFab2tHOExpbGNub0I1RGV4aUE1aXZwVEJqcnM1MXJLVVJWZE0va3A1STFY
        bzc2NmhLblJLbXl1Y05LUVpYU2xSMGY3UVhsY2VGMHFDelVFZDc3czVvM2VBS3pr
        VzY5Tkx0SDljOFcwT2ROcjZYM3dwbmhpTHNsdEpQSjdBT25nOTJjTnRDc1pNem1M
        SVBkOUwvY0dDSzdxTUJnK2xvTjFlUjI3U3A5SVlONUMwUTFVVVQwZEY0bEplQ2VT
        VXJ6WDY1OVIwT3hWWWkzMHZkb3ZqU0ZIU3BrVGlDZ2tOT2hnS2NKMkRER1BNUQpr
        RU44cGtVcFZpTG1BR2xod2NaZS9wVFdKR2ZtcSt0cG9IWi9tSHZEak8wCi0tLSBq
        UnNnd295d0FncGFnUUxQU0JYOW82a0RWbnNwdEJKUVBrbDI2VmxpV0FZCrsxl71o
        /bzL3YAFe2hgCkYrvaPMu9PNovCvflb+GyDdXKJPIUFNxW21ZgoYVJrPb8vIcyhW
        pIKlxwFjkP7WNHI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13zsm6rjnrqmpqnhjxkl6ykcmwpffnua825n6w35k5vzgxvu528qmj9anj29xsxmljw5t2465q5ax6g83k664t9e8exlm4ekv56ztqytggu9fyt5ja9jvj7z8ac94zccm0x72xcpvfs3fwwsn84d9q79swsdxk6pm7ayrjvpnedq9l8qge4mevm4gewxke93dcdcsqc7qd7t79f4ku23hja223rwra4h2nw3wk4dnj7fjpdzneanmlak9vg77dr0tr24m8gfxsctcr50ej7lhtq60g2jnpu5040p6ncfvhdxjxjm4gd6uraaangmhpa4zr9vzyajydfqqwe4x2synz303x9zewpqu7ku6twg9dndrjql4r8hkgjfr6su868p8ruytz8s3ryl7fjl0w93r6c7t082ndje8ch5ekfylgqvx7h90jdeg6as9v6mncwt52gjhpfq9u5prc78tvx3zz9ze2af8rxj4hjysgjhrd6q45rwwv0xczktkcwdee6v8p9re427astprhq4v7qxr83zzpgy4333f7ka6mwewpde2rnhzp405hv8dms28qydwzja90sxue6q22vuk2g3ec9sq5jg8d9hzn0uqvc95rwtacgd35xpm3avg9vrgd83x3tywzc2qwy36t4m547wgzz7lq72u3ujj00nmqjq2802lsuj5pqmkz6m0kjcutzlmx59ry8swnwe8jdnmw96fw0uhn0d24n7z6txk0xkf6g4m6rps3xzm3d5e6d0k2frqyh45vhxtghcnwe9yqrzhzqctjnuqwaksqzy6kf27vwcfqjqx50e6fx62r4p9chkpwk8usurpngrx9svh946fgygssk2dvka04hek8rmh4lavcuctxe9582fe3hnkpjc63vkgsanhvwwjyjt6672yvqwrzcqnz0wcqxqpje7wwzqpfg8nxeuaqx0ysxhgywuw5xpef4ej3svn8qjhu6r97eucdqarhhe5ws2js25rm2xrj7xfl9sjm98uzz68dvuemjjxl9g6nm39dhmmdtwwj4fu2xhhu4yz4ntvj4hmnapcz2dsxfpn4er2yjpuny7ctq9kwh977uze0zngthsuud7nn9w2x2ygg6n55uxp84j3ym25rlg6h2dje22wq539k0uuewg4xalq245pffyh4wz2d9480jgepfe6sqvjudt75a2ggnrc558ussyhznusk2qyeq97c5y59jq4j2rg2yull97p08yjrf7vd6fk8q9epxwa6vq3k6ajxfp8gzaptcc3gdvsmxeuj73d7c2f3xrke02hz42uh3clxeeryuu253jeqh4fjf923290lf2q045x6k3j9emnnyygfzl3uq3fa9qr8qrmnud0j2zaszg0m6nn7tcmxwtfshdq9whyjrq8y3e9kvvx4tsme4cxvnykxkeapjyndnqq5z0t3clu9tqnvtppgk95n3340w9cnnngfx40u6dz54e8mggxvfwsem838nvdhq7czs3eccgztd34cxq0qvan7p3708pylxj23wjt8x72c2ww7we3z6pyc2evuehcepvwvlk5v52433s7nh386xru3d63grlpckt2r2nfk6jqgkczhna95qjpeyccaxd00fjmus52c79knwqufq7a4qrzucdv89msr9k5qskgjpp34y20ceak77ujxn9zgwptc2y947pmj9etfn7h05vgj4ueqv7zfkjuwhdtg399828qnphjv3vrfgsnf6kq8pzzgr5q48fa6p8l2vsxc2artuukxspm2w339zu62v64e54vt562y9gxwl5wkr84ukpz5qj5kpqzgvsltq6tsvwlz53ald087fk76ej6gkvhv42rxjjcnhns0v2f7ymu74xxj4ydm60dm8ulhekyta8e424tmcyuknzyvjzrd8tvfppxakvsx7q233ww8g7l56av
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T00:51:17Z"
  mac: ENC[AES256_GCM,data:fve59IN63rSfcIZEambNnuQ4xc8uxPe45SAxbT9HXz+ZnjgdPyXQrjlYP/YbFUifyXW5sKJyyamn+JpGGB95JWX7e6GVo5Bo57NyzVHQgtSABENqB/QyGidqd0Q95HpCloHeRNzNoNyyR0kE3HgXm/BRj/0C5TCthxGxhDYlUL0=,iv:pidh8uljJmtyaSKt/NH3XoNqUZRQ6TH2yvZ6gykv+vA=,tag:FSB0d7jzLdbmGcGnt7etNA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
