apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:UIqesA24JwhSrxDCxH+kDW4vfw==,iv:Fudvc4FvmI1jG3W8J9AdhJbOeom0PiOyGlbVxSs+R1E=,tag:7UzdK3oK7p3EDb257Ha4VA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IC8wcUN1ZGFj
        MEZxTWFZb1VoQWI1TlozY2NVdUwvOHo3dGFLUVV0SGZNdmZ2UDR0MjZ0b3J6RHpZ
        K2lBMmQrOWU3VDlOdG4zR2Jvck9NQTVrUUhsOEczd21SUHR0NjFaNTFGVFV1Ykd0
        QmtBdDNxcmZ6QWtmeDBBUXl2QWR5WGxydFducVA0Z1lBSE4xVlV5WWhQZGRCdDR5
        QXhCQ0V0c1lMS3k1N1E3ZzIzT0wzdGxRVi93NjVTSkd5WC90K1AyaTVFdHpEUXhi
        UUt0ektuakpUTVRHOWRkTHpDUFRvZTlkc1VOQjFqQ3RFL2ZKN3J0dUVBUmY1TTNp
        NitMUGZkVzNiWGhRTHUyMUxtODB6SFFZSXgzakZCYjd0Rlk2dUdqV2l5SjdGZkl4
        M0lycnZETFpaR0trVWRiVG5xTHE0azZEWjhVbHRJRHo4eFpKY1pTbDdOTm1DMVBo
        bWVvL0IxTVRhbmFZc3ViTzBvbHZvUlhPUCtubnRqUkZqajk2RlJhMU1YdXdYeE5i
        blFyelE5K3R4QmhhcmxwZTdGY2xSbWNFNTM2Z1RxanBzbmMrNm5XTTV4QUpOcUlJ
        eEovL1JFK1BKY21zWXE2WWdMV0FSSlIwSzBsd3JtblByMW5ueDVvQmNYK1Uxa1ZJ
        c1J1UGcrK1VibldiWDkrWDdoNzAzeUZmcWc4WDBBdTIwZjNHOURLaXUvOEdPK0pK
        NG1CWmVURWtsUmYvaTBLd24ySkFuSXo1NFREYlRrV2FnRm0xS0R5akxHWVZFQkpU
        dHNSL1BweWtlcDRrZjR2dDR0YVVkNzFGdWVURUZQUlFmUmJ3SmtMOVhsZnk4ZG1B
        Q1JlaytwOUw0bFJ0STMwd2VzY2pURVJCNzFwZTZvUmVmR1g1a1BiTTJJdkJPeDFa
        aFg3Ti9VdEFRYk85RGdXL3JUamw5MHhTcU5ZU0hiekRRM3lxWjZ1algyRXExVVV1
        ZlJ3ZGdYMEY2UUxIUDdYcEhLT2ljL3RsZWVmSnlNbkhlTjVNQ20ydnNiUHlPQmJ2
        TDROUkhqcW5ubVlVYnNFVXBKY2R6a0Fmc1dvS0NRMzArRUJGV1Y0d0NkdG9ESXls
        OWpEck9mUDhwRE53SkM1Q2FUdnQ0YzNNTFllWTVVNjB0WlAwL0VKR1Nkek1kMlJo
        K2hqckwrOGhJSkFIV2M3RWE4eWZISjVCMnBaNW1DdHZWeDVMUERjakxxd0wvQ1Ri
        QnloellUSEluR3pWdFRVbHBNK0hqdGRVUlBwZWRyemY0azFlaGdFaUZsaktLb0Zm
        Yjd0dW1WYTZRK21Da0gweExDSUs4MjJNN1ZiQm9CUEYwNXMrOXl3TGRVdmsxOWlw
        MG0raUNWMHdjdHJjeXpuUUtkM0cvc1hvK3I3c2g2Z0haZ1BzS0pHRkpqc0hpYVdt
        MWN3NVhOWW96NE82WjF6KzlZcWtBbjRaYXJnRzdIZVNYL3prSTBnbUI1M1poQ1RN
        K3RZZWtaUDJEQzJiNFlmQVhxejYyY1NoUnAvV01Gb0pHYXQ3Mks4OThnZkVNNWNL
        UnVSQ2tVWlBQR3NqQWpnMTgyR3k4ckpHR3NGcDlFVThIVE1aY3BIemJKc0RsWjRM
        YTY2SDQ0ZUMycjI1a1lRM0NWYXNPZjE5VWpjaFlESVJNQ2FFRDVHaFI1cW5pZDBI
        VEJ5Q014M3N1RklpWlozV2lKTk9kQUNCMXFKcjR4UUNIWEZVOEhGVW5Xcmp3T21H
        VWFCQmlGdXlXdUtHQkNIWDJ2dmlwUkF4S01mYWZVR0FHVnNFL1NLVEZIUXY2VFI4
        QW9QQW9TMi9QT3kyMWlDNHByQmJHeUVna0RNTElvQnZtcHU4TzhQbUZLUXhnc3JZ
        bFBUSTEzNEJiMWlYSkxoT1JuYkdadWIzMTU0N3RmdFVXVmE4QzRYRVdpRjZKNFNR
        YmFteGY2bkZ3cWRKOFpmdHdaTVNnOFJlM05RN3M3cXhxNWJMeUVwR1k0cEZUQQoy
        bzFrUWRJcG93RGlJQ25QaC9TY1REa09wTnBDZzc1TkFYU3NhY2drcGJjCi0tLSBu
        RUtlQjRuVm1HMHk4dEhtYnl0elB3TkhuZWRhQTZwb0xoOVVBNnh1YytFChXHF8a3
        0xLujLmmqzH+hcaehCCVRzL5GojBjFYYhBRinHVw0cpTMjzG480WCEbdcDPAUop0
        A1SZ+n3cmQ/HZ/M=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13zsm6rjnrqmpqnhjxkl6ykcmwpffnua825n6w35k5vzgxvu528qmj9anj29xsxmljw5t2465q5ax6g83k664t9e8exlm4ekv56ztqytggu9fyt5ja9jvj7z8ac94zccm0x72xcpvfs3fwwsn84d9q79swsdxk6pm7ayrjvpnedq9l8qge4mevm4gewxke93dcdcsqc7qd7t79f4ku23hja223rwra4h2nw3wk4dnj7fjpdzneanmlak9vg77dr0tr24m8gfxsctcr50ej7lhtq60g2jnpu5040p6ncfvhdxjxjm4gd6uraaangmhpa4zr9vzyajydfqqwe4x2synz303x9zewpqu7ku6twg9dndrjql4r8hkgjfr6su868p8ruytz8s3ryl7fjl0w93r6c7t082ndje8ch5ekfylgqvx7h90jdeg6as9v6mncwt52gjhpfq9u5prc78tvx3zz9ze2af8rxj4hjysgjhrd6q45rwwv0xczktkcwdee6v8p9re427astprhq4v7qxr83zzpgy4333f7ka6mwewpde2rnhzp405hv8dms28qydwzja90sxue6q22vuk2g3ec9sq5jg8d9hzn0uqvc95rwtacgd35xpm3avg9vrgd83x3tywzc2qwy36t4m547wgzz7lq72u3ujj00nmqjq2802lsuj5pqmkz6m0kjcutzlmx59ry8swnwe8jdnmw96fw0uhn0d24n7z6txk0xkf6g4m6rps3xzm3d5e6d0k2frqyh45vhxtghcnwe9yqrzhzqctjnuqwaksqzy6kf27vwcfqjqx50e6fx62r4p9chkpwk8usurpngrx9svh946fgygssk2dvka04hek8rmh4lavcuctxe9582fe3hnkpjc63vkgsanhvwwjyjt6672yvqwrzcqnz0wcqxqpje7wwzqpfg8nxeuaqx0ysxhgywuw5xpef4ej3svn8qjhu6r97eucdqarhhe5ws2js25rm2xrj7xfl9sjm98uzz68dvuemjjxl9g6nm39dhmmdtwwj4fu2xhhu4yz4ntvj4hmnapcz2dsxfpn4er2yjpuny7ctq9kwh977uze0zngthsuud7nn9w2x2ygg6n55uxp84j3ym25rlg6h2dje22wq539k0uuewg4xalq245pffyh4wz2d9480jgepfe6sqvjudt75a2ggnrc558ussyhznusk2qyeq97c5y59jq4j2rg2yull97p08yjrf7vd6fk8q9epxwa6vq3k6ajxfp8gzaptcc3gdvsmxeuj73d7c2f3xrke02hz42uh3clxeeryuu253jeqh4fjf923290lf2q045x6k3j9emnnyygfzl3uq3fa9qr8qrmnud0j2zaszg0m6nn7tcmxwtfshdq9whyjrq8y3e9kvvx4tsme4cxvnykxkeapjyndnqq5z0t3clu9tqnvtppgk95n3340w9cnnngfx40u6dz54e8mggxvfwsem838nvdhq7czs3eccgztd34cxq0qvan7p3708pylxj23wjt8x72c2ww7we3z6pyc2evuehcepvwvlk5v52433s7nh386xru3d63grlpckt2r2nfk6jqgkczhna95qjpeyccaxd00fjmus52c79knwqufq7a4qrzucdv89msr9k5qskgjpp34y20ceak77ujxn9zgwptc2y947pmj9etfn7h05vgj4ueqv7zfkjuwhdtg399828qnphjv3vrfgsnf6kq8pzzgr5q48fa6p8l2vsxc2artuukxspm2w339zu62v64e54vt562y9gxwl5wkr84ukpz5qj5kpqzgvsltq6tsvwlz53ald087fk76ej6gkvhv42rxjjcnhns0v2f7ymu74xxj4ydm60dm8ulhekyta8e424tmcyuknzyvjzrd8tvfppxakvsx7q233ww8g7l56av
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T18:38:02Z"
  mac: ENC[AES256_GCM,data:exQCzHrIq8v4HYCnUXpDWBEZkxUd4vkFpIBYbqF9ju5J7glfoQtIhBFkCiqeOBOMJ3uUI2ZTsmyqv/4WlPG2JiuHurQ3i/6HSk3F+Hi/jYg+gNdMvSMMmw7PqZb+IeQjE4yzhZVtVarswMpqAudXiBiBwW7bGIGUdR1d5GvxObk=,iv:4m1NuZIHPPja34NtV8PgYMlfxGEg0FzBtkykmSQzqi0=,tag:2aN6K6sbHg4SrsZBn9FeVQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
