apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:tQEhjoANSFRx5rM0pbbqy4WLlQ==,iv://xOWzik3p2uDAKj33B83v7o9CC3icMG/XPA6zNpHgo=,tag:OEKAMZeQRj4I7ukYC5mYlA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHJ6MEg0RzYv
        dDllMFhYenFoYnhNZEl1bUhSZ3Roc1E4V2FQbjFxemd4TDlkWWQxZGVpYWJ0WjAx
        eEg4eGdRMzhJVzg5SFBNRFBRNTJvbGxaY0JRK3I0NlU2NS9TMHNtc2E5Y2N4c3F2
        VEpWRmFHdm93UHQ4NzhNaE9sOXFDNzQyeE8yRkROWU96VE51NWZ4OHAzUGs3MEpM
        NUpMMi8xV1JBbzBaV3R0RWhZR3FPUzFWVzE5UjFqY21Kb2E4LyszOVRXL2RROW9E
        NG9Id2VwTC9DdmJRaFRQOGxOclp6Y1l2WFZYbmVsZUZWYkk1bmlydldzVVhvY3Vt
        QUc2TXcycXVyMlJsNVVYK29YbHVyR0dXZGNhWkVGS1VXM1pqdXlCRjJPdWVBakZa
        T3hnZTRrblVGelIxK1crbjlYS1NGSy9sOE5WMlVEdDQ5cVAzcEgzMU0rNW0zcFE4
        Vk1EQ1FFVUJPVUFJOGRER2swVXJnMnVSMG5va2p2dURCUG5Dc2RwZDF1RzVldWl1
        bjVqWFVndG9tOVVJbkNsZ1lTQUFLTExqN3hGSDd5NzBtOXJ0SWpJaG9kUDB3OWda
        VlFqMXVPektTK0hENVA1OXBtVEIxUnZJTmZGamYzaHBvTUphZ0FPUjVkcWc1Y0F0
        Tkk5RkI4MjBGcFFya2tXQS9FUXdnQUpTdVZZdWx4MTN0VGgyWFFRaisvaE1XbnZm
        cncyS3NNQW0rcHpCeVBZdlBBZjF1YUQzak56NFoxYytERXdoV0RjT3d1ckE4UDdH
        aHFENFJHVDBrZmJmRENSNEdlUVFQRDlFc3puMlBwTU1KRXV5ck84T2l0bEg1djhR
        R1dDZ0tMTGhuaTNzazh2RlZTc0FKK0tOaEY5ajFzQjBZcXU3WlQ5Nnoyb01sMUI3
        S2J4NUVyZWVZb2FBV1I2NDA3ekN0Y2FmKzNQcFpBQnRjR0U1MjBLeFRlMmlQZlpj
        YzQ2bDEyQUJhTVo0K1NYSSthQktKM0xldEZmb1JqVndobDhtSlVFVGxGSW5oRFRv
        U3lmNmoxWThUeWY3UW1GdWh2bEpuZ2piZUlabzlJWms2WFhudTJoUndGNUp3Q3M5
        RGVGRXh6VHNma2IwTlo2Z2NUcGpZSXNMOWU1YTlYelhFWG1wVmM5dWtaRzcvc1ox
        ZllnUlV5S2IrUnNPMzZOTm42NEV2OXU2ZGMrL1VhN3BRUnNDUTFFc1JQQ2pkeHRL
        RVphQ1NtUk5rZmVjZmJFVDVJZDRSQlJySTkxY05XWkdxSVhGeG1Ob2FUYTZQTFpN
        bXlxRjRLK3F0ZVJyenBqYlZpWllUUmZWbzZCdlJzek9qdVBnOU9ZWGFuTHhaeUhk
        R1o3dC9RZHhGUTh2VVFSN0JINXJ2N3E4NldGTURYSjlSLzFOQ0JBRUJKZ0VUbkNI
        RGNVbG45TG1TVkZrdWUzRlNDbXhBNjVWTzg5SVU3cUswc1Nxa29MOXYxRmNwVDJZ
        RW5NeTVUR2w2UlFpUTBUd0puaEVMbE5WUTRUMUg1cXZhU0svQ2lkZ0tKWnpLMlFi
        RnlDQlZsR25tR1FaSFNWQzFuN1F3UHVYMCt4WlZLaEVVRS9zU2x2MGc2dVZiWk9X
        M01xcEZGS1VsTlVEODVoTStPTk1JSG1aN2cyRDF4enpDdEgvSitYOWJrbE93TXI4
        VkRBWnpVSUNkdi9wZzJnZTNHNUo0V28vcUtFSFJHelNzeXhHbGxmUHR1a0pJd0dr
        NVJBaUxGSExsMkxodWtoc3NHb1pPaTdQM2VtSDRKbGZQUm9Gam9KSmtvRHlNU0tB
        eU0xaFAxTVkzeWlrcXU3SWlEZGdrb1dOayt2eGpxWVFTYXJBR25RRC96VmJ5VmRx
        eExiZUdoanYrMUNJRmtTQWdvUXl1ZHluR0poODRTSGdZZjdua1QreHljcERJcWhy
        RDlsM0NtckFuUjhOMldrbmE5cjhNc2t1RGdrU09jMjdiRGVoc1I5SFVRbVdUdwpm
        Wm5wdm1TY2RIbFpjQ1lqR0ozS0VtV1lseEdkSUo5SzM0TUJaeUpoczNVCi0tLSA4
        cC9MQlBjRW5USjEydHlqbEJaWVdwd0M2bEF2ZnNRbDJueEU2c3hUV1Y4CiXGmoAX
        d3D8X4DdT6xg715Cky+vtUwwz56obfaE5icezneqm6f7QkTc7REObCrHMfyQHk5o
        17nDhLzwiUKa5nA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13zsm6rjnrqmpqnhjxkl6ykcmwpffnua825n6w35k5vzgxvu528qmj9anj29xsxmljw5t2465q5ax6g83k664t9e8exlm4ekv56ztqytggu9fyt5ja9jvj7z8ac94zccm0x72xcpvfs3fwwsn84d9q79swsdxk6pm7ayrjvpnedq9l8qge4mevm4gewxke93dcdcsqc7qd7t79f4ku23hja223rwra4h2nw3wk4dnj7fjpdzneanmlak9vg77dr0tr24m8gfxsctcr50ej7lhtq60g2jnpu5040p6ncfvhdxjxjm4gd6uraaangmhpa4zr9vzyajydfqqwe4x2synz303x9zewpqu7ku6twg9dndrjql4r8hkgjfr6su868p8ruytz8s3ryl7fjl0w93r6c7t082ndje8ch5ekfylgqvx7h90jdeg6as9v6mncwt52gjhpfq9u5prc78tvx3zz9ze2af8rxj4hjysgjhrd6q45rwwv0xczktkcwdee6v8p9re427astprhq4v7qxr83zzpgy4333f7ka6mwewpde2rnhzp405hv8dms28qydwzja90sxue6q22vuk2g3ec9sq5jg8d9hzn0uqvc95rwtacgd35xpm3avg9vrgd83x3tywzc2qwy36t4m547wgzz7lq72u3ujj00nmqjq2802lsuj5pqmkz6m0kjcutzlmx59ry8swnwe8jdnmw96fw0uhn0d24n7z6txk0xkf6g4m6rps3xzm3d5e6d0k2frqyh45vhxtghcnwe9yqrzhzqctjnuqwaksqzy6kf27vwcfqjqx50e6fx62r4p9chkpwk8usurpngrx9svh946fgygssk2dvka04hek8rmh4lavcuctxe9582fe3hnkpjc63vkgsanhvwwjyjt6672yvqwrzcqnz0wcqxqpje7wwzqpfg8nxeuaqx0ysxhgywuw5xpef4ej3svn8qjhu6r97eucdqarhhe5ws2js25rm2xrj7xfl9sjm98uzz68dvuemjjxl9g6nm39dhmmdtwwj4fu2xhhu4yz4ntvj4hmnapcz2dsxfpn4er2yjpuny7ctq9kwh977uze0zngthsuud7nn9w2x2ygg6n55uxp84j3ym25rlg6h2dje22wq539k0uuewg4xalq245pffyh4wz2d9480jgepfe6sqvjudt75a2ggnrc558ussyhznusk2qyeq97c5y59jq4j2rg2yull97p08yjrf7vd6fk8q9epxwa6vq3k6ajxfp8gzaptcc3gdvsmxeuj73d7c2f3xrke02hz42uh3clxeeryuu253jeqh4fjf923290lf2q045x6k3j9emnnyygfzl3uq3fa9qr8qrmnud0j2zaszg0m6nn7tcmxwtfshdq9whyjrq8y3e9kvvx4tsme4cxvnykxkeapjyndnqq5z0t3clu9tqnvtppgk95n3340w9cnnngfx40u6dz54e8mggxvfwsem838nvdhq7czs3eccgztd34cxq0qvan7p3708pylxj23wjt8x72c2ww7we3z6pyc2evuehcepvwvlk5v52433s7nh386xru3d63grlpckt2r2nfk6jqgkczhna95qjpeyccaxd00fjmus52c79knwqufq7a4qrzucdv89msr9k5qskgjpp34y20ceak77ujxn9zgwptc2y947pmj9etfn7h05vgj4ueqv7zfkjuwhdtg399828qnphjv3vrfgsnf6kq8pzzgr5q48fa6p8l2vsxc2artuukxspm2w339zu62v64e54vt562y9gxwl5wkr84ukpz5qj5kpqzgvsltq6tsvwlz53ald087fk76ej6gkvhv42rxjjcnhns0v2f7ymu74xxj4ydm60dm8ulhekyta8e424tmcyuknzyvjzrd8tvfppxakvsx7q233ww8g7l56av
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T16:14:48Z"
  mac: ENC[AES256_GCM,data:PTvE6NM9xjhRoDRZF9Z9T8rF09PKiM434G1O+xB3+LSowzKA2Wqn545mSdj+S8C8aeQAFp5v7JYyAzVoaxgFqiTxKBsLvfE0n+N8HzQy0J3pZKNsv1fn6m15Eiv/WvCm3C2U2p5aFUkV3g4879mk7ofRl54njD7Crm7sj2Q9OS4=,iv:jhQQuPWbjGp9Wmj5nmOwCANofEdhQTHHW0gCQgMdU0A=,tag:KSPdU7unkzbS4G2dtdKK4w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
