apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:fHCf76jyTlmf1OCloEwzFwRP9OqeWpOGgX75O3kWqyY=,iv:CwW3uqXravMPR8iUTSFBpc/5HAKyz8pQILGXko/v2a0=,tag:TZcvgwSBFk7RLDXsXZSQ7Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IElSa2E5NFpK
        Q0w5U2N6ZlBRaWVuTUtpS1FpZ1E0RlIwdXFqdEsxMHgvUEdJWi9pRHZ5T1BQcUh6
        QkJXMkZOcDVhOU8vZXBFc3hhSjB3ZkQwRUlibU4wT0VqMENLa0RBQytYWXkxQ29l
        UzBjTDRUaGdiZVp6b0liendwa0VqUlB3T2YxWlVqTEF0S0dIaVAzcUx1N29UakNu
        VGZtV2NRbVdEMjNrcFNLK2ZaWlpTNVdQUmlEUU1VYnZmaEE4UWZVVjI3L1NhZVVF
        TFIzWWVWRzA4NjhqNE03Ujl1eXBXVWZKQTZDdmZGeEFqK0U4MWJqTW9GNWZENjVq
        TTdQcmNjRFEzd1o2ZTFrZ2lwUVBORVBHUmJQNHg2VDA2dkVLcXE2bmZIVWpXWFp5
        SjhGNGRReTNUYjh3K0lnWWpJb25CY3RhWEZKamhZYVVmODRPc09CWms2dXVhck9q
        S0hCalo4b0Zld2tUcGdLZ1hpcmtpK2ZxOUhjaFZ4OGNVZ0oveHV0MVI3MnNaRHA0
        S2ZJNTNEV1pTNTdlbVE2eitoMjBBbnJ3UDl6THNiTGx1R1J3ZzZUdjNoazVaYUJR
        eGRDaDcwVUsrYzhyeHc4UWliM20yTmNyWEVMRkQ1SUltNGYxd2dXNWV2WnBLNzVi
        ZVFRb0NJSklrUS82c2g1bWtka1l5ODMxYld0WWhxNE5PTU5kbHZLYVYvdm10NEIx
        Nndnalg5Y2JvMFlESXZxbmMzeTNQWjUrQ3pydnlGTWlEZVBsd1R4RmFDeXJzU01u
        N2VNSE5mUjBURmVYQWlYUkl2RlpMSkppUXlrNGhCekN1ODZNd0E3cG1vWHBkeFJQ
        Mm84MHEyRVcyUlNWRVcya29RNmh2OEJtOUo3d0lJdmZ1OHFUSFdpVFkwckVoazBu
        M1pQZWtrK3U5d3h2M2FGM3FMaklJaVZiUUZXZEM5L0xOeHR2VC85eVJjZllqd1lK
        OGJmZVhic0NBNzVqT2ROOW1BYUNwQnZ1Z1liektaT0hHTDhWSVV4aGNOUmV2Qk1h
        dmlnQlJOY01XeGxGa0VGcGZFWUIwbnZlVG9IRHRwM042MEE0NUhaV0RHZWU2MDdq
        cEh0bVNmSDU3aG9aRWtPZkI2dUtEdllLN1FJVXkxbnlFYnY3MlFqUXFrTE9SK1Ay
        QmtvY1N1REtVdkVYdW9Hc3dTYkhzWisvSTlWU3hqU3YybVh6V211NWNScnp6UzBo
        T3JVWVNuS2JsblMrNlZoVEU3VUk2N3ZnZlNFTUVocVc3ME5BRHdyQjJIK2lTYW1y
        aWxxTjNERk5aUGFtcGs2d3QzNS9zKzJFZHcrQ2lvQytxb3BsNXNTbkkzTXppR01N
        dkM5MFJCN3VFc1Y3dXo3V2o0eE5xdjNVNU0valE3c0pKbzMzelpSMjlzN1NGNWtT
        K2RScTRhZ0ZGQ0p5SXN4Y1dhMVRNN3d3dWxFdTJEQ203UHZtcGN2VzMwMVdhLzBN
        ODRUNWkzVGVITWxSaHEwUlFhRUxsVjdhb2ErdnlTYk10TDc1RU53Y3FNZHBKZVFn
        dE1jQ0dDS1FuTEsyMnBzRzRmODlnWmpYUjFBcmVOSEVPZmtjOUVwdFc3MTFuK0FG
        dElmUDVna1d2c1BRdEM2TUNlUU1WVk1aWW1CWk5FVTJSTjgxRi9ZaCt4NUZwaUc2
        VUdMOElJeGJzZXNEd2k3SWMvRlQyaFNsUmh3NmJpOHhyUWtpcjVmRm5HV3FNelYx
        YlBHKzlaWTNTMUQ1d1pMZVplVXk4VWpPZHl4dkRIb0hPQXlrcFlIcDdkTXBMOG8x
        RTJKa3lXRXRZTDh5SlFWUkxVc2dXTFNldWk3SXZQMFoyOFRMb2ZzRFhJK0NqOGNi
        cmtpNEFBTVBXNmxaSlQ0KzlpQVJWNytmSDBxRml4bzZkZWsvR0J4M2VPcGh2b2dW
        UHpuYlpNR1ZiTnUvdURzS1VaR3BaazlhVWFaaHFPcnhXOVM4VmhWR1dKaDNYZwpO
        OEpNKzVuQ3pXRllFcjBES1I4MkxwcHg0eHhOL2lPTjR0TDZWT0RnRFZFCi0tLSB2
        SUxCL0RZK09OdUZmQWsyQThNRDNVZ3lNSlAxd0JOWXp2N0RLR3J2RGUwCsmwRX+z
        zLDmpA6FQDK1Y8oqlxsdySV7wbdyEnzh2BnDgeFZii6+qsgL5PwcJdNx6/no4a5Y
        sWdVhSS5qXy9p2o=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13zsm6rjnrqmpqnhjxkl6ykcmwpffnua825n6w35k5vzgxvu528qmj9anj29xsxmljw5t2465q5ax6g83k664t9e8exlm4ekv56ztqytggu9fyt5ja9jvj7z8ac94zccm0x72xcpvfs3fwwsn84d9q79swsdxk6pm7ayrjvpnedq9l8qge4mevm4gewxke93dcdcsqc7qd7t79f4ku23hja223rwra4h2nw3wk4dnj7fjpdzneanmlak9vg77dr0tr24m8gfxsctcr50ej7lhtq60g2jnpu5040p6ncfvhdxjxjm4gd6uraaangmhpa4zr9vzyajydfqqwe4x2synz303x9zewpqu7ku6twg9dndrjql4r8hkgjfr6su868p8ruytz8s3ryl7fjl0w93r6c7t082ndje8ch5ekfylgqvx7h90jdeg6as9v6mncwt52gjhpfq9u5prc78tvx3zz9ze2af8rxj4hjysgjhrd6q45rwwv0xczktkcwdee6v8p9re427astprhq4v7qxr83zzpgy4333f7ka6mwewpde2rnhzp405hv8dms28qydwzja90sxue6q22vuk2g3ec9sq5jg8d9hzn0uqvc95rwtacgd35xpm3avg9vrgd83x3tywzc2qwy36t4m547wgzz7lq72u3ujj00nmqjq2802lsuj5pqmkz6m0kjcutzlmx59ry8swnwe8jdnmw96fw0uhn0d24n7z6txk0xkf6g4m6rps3xzm3d5e6d0k2frqyh45vhxtghcnwe9yqrzhzqctjnuqwaksqzy6kf27vwcfqjqx50e6fx62r4p9chkpwk8usurpngrx9svh946fgygssk2dvka04hek8rmh4lavcuctxe9582fe3hnkpjc63vkgsanhvwwjyjt6672yvqwrzcqnz0wcqxqpje7wwzqpfg8nxeuaqx0ysxhgywuw5xpef4ej3svn8qjhu6r97eucdqarhhe5ws2js25rm2xrj7xfl9sjm98uzz68dvuemjjxl9g6nm39dhmmdtwwj4fu2xhhu4yz4ntvj4hmnapcz2dsxfpn4er2yjpuny7ctq9kwh977uze0zngthsuud7nn9w2x2ygg6n55uxp84j3ym25rlg6h2dje22wq539k0uuewg4xalq245pffyh4wz2d9480jgepfe6sqvjudt75a2ggnrc558ussyhznusk2qyeq97c5y59jq4j2rg2yull97p08yjrf7vd6fk8q9epxwa6vq3k6ajxfp8gzaptcc3gdvsmxeuj73d7c2f3xrke02hz42uh3clxeeryuu253jeqh4fjf923290lf2q045x6k3j9emnnyygfzl3uq3fa9qr8qrmnud0j2zaszg0m6nn7tcmxwtfshdq9whyjrq8y3e9kvvx4tsme4cxvnykxkeapjyndnqq5z0t3clu9tqnvtppgk95n3340w9cnnngfx40u6dz54e8mggxvfwsem838nvdhq7czs3eccgztd34cxq0qvan7p3708pylxj23wjt8x72c2ww7we3z6pyc2evuehcepvwvlk5v52433s7nh386xru3d63grlpckt2r2nfk6jqgkczhna95qjpeyccaxd00fjmus52c79knwqufq7a4qrzucdv89msr9k5qskgjpp34y20ceak77ujxn9zgwptc2y947pmj9etfn7h05vgj4ueqv7zfkjuwhdtg399828qnphjv3vrfgsnf6kq8pzzgr5q48fa6p8l2vsxc2artuukxspm2w339zu62v64e54vt562y9gxwl5wkr84ukpz5qj5kpqzgvsltq6tsvwlz53ald087fk76ej6gkvhv42rxjjcnhns0v2f7ymu74xxj4ydm60dm8ulhekyta8e424tmcyuknzyvjzrd8tvfppxakvsx7q233ww8g7l56av
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T00:51:17Z"
  mac: ENC[AES256_GCM,data:aFVYtk0vz86QfwFzp+2c8sXJuciM1eg4WywGiPde0WHyqB3uy7ZdfyrmSZ1WN9lbVV6M0WOXkbzJoY5mhM+/UDUV4NOSFMCFqjvHYTbAyeoNNrFEaOYcsP5xr4wSnPjG41Rl+xbJZij7y26csbSmcn3qgf/znAKkwzir/pfTWVI=,iv:3bYQJsPm6QD8PuBnTfMcq51ThPtOYpAAdFT1jlP4t4I=,tag:JwGSZXnkElsFtHtRFUN+3g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
