apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:ANIMxs1uDORkoh/7Bz1mkllTn1gM2mLpPIaAUkDBJzE=,iv:3AKhdV3XPrHH4wpYpBRflUY6NcQQcQ4zRR9UPZdAUVs=,tag:04u8+RTTS9NexyIo8OuQAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFpMY1pnRDU2
        a2R5SElaNHF6andZeVZFNWhFVlMxSEcvU3ZnUnNxT2tpdGZoeXRyVmRVb21qWGhK
        RlJEbUx5ZXN0L25rS0JSRHZMdDhGZlNFUEtuSlh0ZGlvYktBR01CYmhnVkdIZ08z
        SXZ1enJFczB6Z2ZEZDhrRmtQZjAxSDg2QW5tcTcvYUpFY2NScW5JemFWOE5BQjdH
        MXFzYUN4V2Q2SlR6ay9CZDlWbDl1cVlXYS9ZVi9xWWRlOU9hV3JFdmVFNjlYOUIr
        eWp4MHg5RHNXMkZuSU5DcWE4cUNKSktlYk41RXNwQ1g4d1pyeDhBdWZSMWNFNUtr
        MnJqOHJOUnlzU2pqRG5OMktBQVg0Rk5namEwVW1tcFJ5QmcvUDc1K3lSbkFMZ0p6
        aFNsOHQvNXBXUTNlTmN2Q3lFMEVjR3VNSGJsdWVOVVRrcldoWUZ3NW93Qm9YRFBo
        R25mSlVYUkZaR0lYOUdZY2NNUFF6eE1VV2lPb3RuOFpYSG9KWXAxT1hCQUw4d252
        ZmdzNlFMSSt0ZFNyaFArUXRVRkJudGhWbjRoRGFjMEhhWk9LL3VOcnd3MW1oVlVN
        eEJmYmExQlZ3M1grQTE1a2VGRURXQWozS0FzeUVUUHpyMDlnZWkvaUZaVTltYjAy
        UVA5Y0hvbGtDUmk5eDBFR3UwMGE5WWlwYWRpUmlRZUJmSldTWWUrc1hGalBCZldi
        SWtkeWorK1IvczZ0OVhqMEJxT0h0WnN2N2IwbExVeGNZUlFyaDJXSVZZYnpPS0Ex
        eHJNWE9USHVQUGx5RmFQSmFsUUhKV3BsM0dxL3B1WFA3WUh0N25LVUViRGJVWThm
        TWlQcnc3NDdvb0ZSWW5GVEYxbVJTMVkzZDV5RForV2tEc2xVUDRQd0kxQVVUZU4w
        NUdDUERMUmt4OUpjUGkyakYvelNMUStIdG1vOHlCMVBxYXFTM0UxSnZhNlZNNnFh
        dE5lRGs3MzRtTy9zcHdOeTRuaGd6cFI4bTk4QjZVRmRUNUEzU0ZocXJZN1NzTXNh
        Z2RBVDRGeTU4QW0xSUcxWWhyR2w2ejc4eHZ2cUkzbHlYSTJDUjQvMVpQMnFmTmt2
        RUNyZnZYRHJQSGJzSTRvTjM4KzZhaEdhY3JDM2JXSE5aeG02YjJmejdiS3ZiWUJJ
        SjQ4MUsxYitJaWNYOUgyMzdmMnBBcTB0ZklVMVhIbWhlWWtsamU2RFdaSlRCZzJo
        anVBaUJVS1lYSk9xOWJJRjY2Qms2NWtqMmcxangrNjBuM0xQVk16MGtXanBuaU1C
        eEV6eWVsVG5EZU95THpqeU9odDhKUTZTRklwRmNOZ2N1VXJBOExQTmFkV2dXRzls
        VnZHMnBKODZYOXB4L213UkRRVnR3ZjcyTlJRc3RXaEtiSHVMZVJFVjMyb1FZRUdw
        dkhDNGhMRDJZK1JZSE1wNXpDbzhYMHV5bkpRUUtKSGVPR0xYbjdXRksxOE5GclU4
        NWJvWmNOVCtDcm9jUG1wRVJNYXhURlcvSjBHaGhEMjE2NDBBdGduaUthbHgwNFZy
        aWJBTUQyd28rSlA2cDc0M21KSGJIZTJNcjBqUndhckNxWnZZZ0E5QzE3c3Y3dGhS
        WU9MMWRYWnJudHh5L1htM3V0czgwRWswU0gvLzdkVU5jWjMyMSttRmZma1hDQWUx
        VjF6amt4WXU1d05Wa0RYMjlURU1xRkYzODRTL29IUktkK3d2b3lvRkNzRTg2Mktp
        OUVkWHFIZWVrY3pSVWtQTElNcFJHbHJxNmlYMzc3QWlSeFhIaXNucVJ0aTUwcG1Q
        QjRxTmhzQ2F5Uy81MFBuNElaKzVLNm1lb0V1YStFNmRjZnZDalZDa2ZjL3JDS0pV
        WmlTN3lsbkJOZm0yVlpSV1UrN1lwTG1jVFZTb3pzOHZFR2c4SFdHTk9VekVleS9R
        YUlZUUNsdGxQY2Z6QWE4ZFpQenZZb3d2MFAxY3lFUXBCUTJIUHdNSzRiSWVZZwp4
        a29RMk00am1ucmxmL3NxNUl1bTNmd3NvUDd2OGFHR0J4eEt6RHFpRGRzCi0tLSB1
        M2NZWXJmZUdBYkwzV2ltMm5NSWdNRE5lSEgxUTVEbDk5bTFYdDVlVnVFCvFXJzS/
        fhQYfOg9TNQB3sFmwJmoERgxRki/Jp7V/DCDvVdWLVeMCrCQBmT3n8/NBy2QWMTD
        35TROJFeMyYw2Ls=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13zsm6rjnrqmpqnhjxkl6ykcmwpffnua825n6w35k5vzgxvu528qmj9anj29xsxmljw5t2465q5ax6g83k664t9e8exlm4ekv56ztqytggu9fyt5ja9jvj7z8ac94zccm0x72xcpvfs3fwwsn84d9q79swsdxk6pm7ayrjvpnedq9l8qge4mevm4gewxke93dcdcsqc7qd7t79f4ku23hja223rwra4h2nw3wk4dnj7fjpdzneanmlak9vg77dr0tr24m8gfxsctcr50ej7lhtq60g2jnpu5040p6ncfvhdxjxjm4gd6uraaangmhpa4zr9vzyajydfqqwe4x2synz303x9zewpqu7ku6twg9dndrjql4r8hkgjfr6su868p8ruytz8s3ryl7fjl0w93r6c7t082ndje8ch5ekfylgqvx7h90jdeg6as9v6mncwt52gjhpfq9u5prc78tvx3zz9ze2af8rxj4hjysgjhrd6q45rwwv0xczktkcwdee6v8p9re427astprhq4v7qxr83zzpgy4333f7ka6mwewpde2rnhzp405hv8dms28qydwzja90sxue6q22vuk2g3ec9sq5jg8d9hzn0uqvc95rwtacgd35xpm3avg9vrgd83x3tywzc2qwy36t4m547wgzz7lq72u3ujj00nmqjq2802lsuj5pqmkz6m0kjcutzlmx59ry8swnwe8jdnmw96fw0uhn0d24n7z6txk0xkf6g4m6rps3xzm3d5e6d0k2frqyh45vhxtghcnwe9yqrzhzqctjnuqwaksqzy6kf27vwcfqjqx50e6fx62r4p9chkpwk8usurpngrx9svh946fgygssk2dvka04hek8rmh4lavcuctxe9582fe3hnkpjc63vkgsanhvwwjyjt6672yvqwrzcqnz0wcqxqpje7wwzqpfg8nxeuaqx0ysxhgywuw5xpef4ej3svn8qjhu6r97eucdqarhhe5ws2js25rm2xrj7xfl9sjm98uzz68dvuemjjxl9g6nm39dhmmdtwwj4fu2xhhu4yz4ntvj4hmnapcz2dsxfpn4er2yjpuny7ctq9kwh977uze0zngthsuud7nn9w2x2ygg6n55uxp84j3ym25rlg6h2dje22wq539k0uuewg4xalq245pffyh4wz2d9480jgepfe6sqvjudt75a2ggnrc558ussyhznusk2qyeq97c5y59jq4j2rg2yull97p08yjrf7vd6fk8q9epxwa6vq3k6ajxfp8gzaptcc3gdvsmxeuj73d7c2f3xrke02hz42uh3clxeeryuu253jeqh4fjf923290lf2q045x6k3j9emnnyygfzl3uq3fa9qr8qrmnud0j2zaszg0m6nn7tcmxwtfshdq9whyjrq8y3e9kvvx4tsme4cxvnykxkeapjyndnqq5z0t3clu9tqnvtppgk95n3340w9cnnngfx40u6dz54e8mggxvfwsem838nvdhq7czs3eccgztd34cxq0qvan7p3708pylxj23wjt8x72c2ww7we3z6pyc2evuehcepvwvlk5v52433s7nh386xru3d63grlpckt2r2nfk6jqgkczhna95qjpeyccaxd00fjmus52c79knwqufq7a4qrzucdv89msr9k5qskgjpp34y20ceak77ujxn9zgwptc2y947pmj9etfn7h05vgj4ueqv7zfkjuwhdtg399828qnphjv3vrfgsnf6kq8pzzgr5q48fa6p8l2vsxc2artuukxspm2w339zu62v64e54vt562y9gxwl5wkr84ukpz5qj5kpqzgvsltq6tsvwlz53ald087fk76ej6gkvhv42rxjjcnhns0v2f7ymu74xxj4ydm60dm8ulhekyta8e424tmcyuknzyvjzrd8tvfppxakvsx7q233ww8g7l56av
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T18:38:02Z"
  mac: ENC[AES256_GCM,data:uaobtSOfsUpX0r2aMZKy7WMmdvZRGhhoBBWJMufsTdifPZ5/Z3HUoVkJaocMOhE+UjBspErLf3HJMvigOKZCLpubiCZtF1+PJWyyqMYvZwczqixzee5VRK+RvdzwUnJlc7dlqTDbpVdN86uV0eWWQKT/dsuQqD764V7DpZO/mxs=,iv:4pQRqM0gmvtOdZUSY5ioDSg9MGzb20+ZPytciAEYir0=,tag:PMFL8k0mqDGd8cXxDZLNFQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
