apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7d0gJldF3Ghsop6oo2Vtmoyra+/4jiCi45/I1PlF/VG34Mk2jf+DaLDewyixfLjPj3UsGxE=,iv:MFObxez+wAwy8hFH3U61aeQZ8N9N1TFb1ryHJu8d2yk=,tag:kTP8KmQx89hBaZcsybr5xw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFVRZVMzQWdR
        ZlVQcGRLemQ5TjVRWEpMOTVLZ3YzU2Zqa3lBNmhDRnlodjdGSm5ZeENiZDJKVlVO
        TUJJK0RPU2hBWTV1cmFHc1YwZUVMdkN4VU9CSzhndkl3Yk82L1kzM0JoRytqYUFS
        T3V3NnMzWjBBREg0eEJDaDlCeHQ3eWhTVFFSMVJlUmQ2WjUxcTJhNE5DaXdyelgx
        RWVHSlRESC84R2toUFd5b0N5WnUrVnVReEF5N2FaSDE4V0QzU2kxRXJJMDFFS2Vk
        bGxIaVhnK2hraitmSlkwT0V4Y25VeGxUTzFma1QrUHdNcGlGQkZ0Uk8xQ2VBWU94
        c1JRZXdOTnlHNlFFK1poeTZLMWpqY1hqMnArQ1JYSDNRZ0JkS1VRa1ppNjNucTcv
        TEV0bnI2bUFOS2ZiWlVJRVh5bTBYaVpSMytKS3lkUWlPa0JmMUVnbXduTWd2UmVS
        NklPWnRxOU9VT1ZJTGw4OXo5dnljMlcwejFxM1ozVUx2UEJMSjQ2Q1owYlB4RzFz
        VzZwL3B1WkY4UlpRTVhqcmtqSktMMlpZZDVXc1hlenpqREJpekpBT0l4V3VIUXZz
        WEdQZjdhR0VlSS9Ca090NTE0cm11WS9RNmhDd2pvaGFvNmZ1azdSMmVwUTRIMnh5
        K0xCQUN3WU5MdTVCS2Q2ZGdrLzVPTVdiU25rNTllUDEzbGMzdVdKOFdtbTg4c0pJ
        cVlBVEhGajBqOWJNRjFhRmhVajZXWUpvUENNNFZJVzh1OExXM1ZtWFVOc21aa0NJ
        NjIvZkVsVUNxaDNRdG5tRVN4OGhNSDRBRm5XU29jcDFIank0b1FJZU1wSkgwdE5q
        b0R1RlMvb1hkM1dRY1RaeHNGWWdwV2FDTWUzVGdzQ1k1UmtGYUZzSDAwZTNWSjlF
        VVppZmVpSzQ1bk9BanhtQm5BY3pxZFhHVXhnWXhZRE9ST3Q4QVl0elpyUVhGOXYw
        U1lqbzRNM29oNFpTN3ppV0xPNWRLZzhYNEVIVGNva0xZOEJodStsaWZNVjFoY0hB
        UUFVR1VFWmlRUFpJMU12NGMwUjBtL0h3N2RvSjZielJmY2xER3pLOUZoT2tJQ3Fp
        TGNIOE1UczFmU043V2F0SmxyejI3Y3lZVjE3WmJ0aHlFK0NnNHhieVhCMUlGU2ky
        U2hOSCtMdk1BSFlTTm5SdUkrN0NCUzdRQ2x6cVIvWURJSm5DeHU4SWhydUgyTmpZ
        WVpXemUzYlpwTk9YWWlaR0k3bnVqZEMxclphWE8wbmtMVE1OdEo5RUFPTlF1a2lX
        cmVTdyt0cC9kbXUwdWYwUTRBQjkrNTdqVmZ1TlQ5R2dxcGI0SUwxWExmSDBudlhp
        dm5wQit6eDZnZDBHRDJzUTNWLzNvcmlPT2J4WEV6aGRmUVNMTjdYeE0yeHBtbVM0
        UEh4KzlySi9acXhlcWRLQnkxZThNSFJNMFQ4a1IwWW53dktzQjBTVjVaOXZxdjdF
        ZVFGZGx6STQ4aDI4dm85bzFOVDdCK0JkMFBoR2pGblFoYUxhSW1iZEdSMHhOOFlj
        KzU2enhNTURweGdNR3pDcGhYVkU4MC9BUmtyaUVNcmErSjhJcnJvaThtenZZMnN0
        VndyOGdXN3pQOVNWUjlKSjBWdTR1WjBTZTUxOHEyb284N0I2L21pdm5tdS9WblAr
        UGNTcnU3cWZkNHRPQ01CK2dPZ2ZhTHUwd1llelZYVnRkMUI0L2VvYjM5YjdRaUpO
        LzQ4NE1OV0RoVXRJZWdybWhJWDdDSnl1VFJZYnl5dGFLbEN5clcrWjl3SzhQWXB6
        NVluQUFUMUdiZXc4VEFXUFpWOXlTeVR2ai8wVnRnRWE2MXUxcTBTdmlXTEhaUjZx
        b2xlL05rYTlsOEtYQk5FYThEV0U2bk9WZC93N0JBUlJuVTZsaTRBWGl1VjdSbDYy
        emYrckI4blFmVmJzNEV4UlF5Yjc4TU9KSnRuOGpta1ZCdDlaeUVEMVozRFlVdwpz
        SHJ5ZUZoRloyZ2s4WDdqZURaUXVjbkhSOG5kY2FIa3poOG5yQWpVYW04Ci0tLSBn
        bXF1UW5HS0JKSEpSb2ZnWFlCNzhpbHVOQUNmdUFoc3B2UTJQMDJHeXZZCpoS/EB6
        YrNxlkn1zXDeMLFp1jmY15Ea6pKpx/yzzrTGqiqNPy2dZ2REF2Xnhw/8nG4HIQ0r
        Uz1lW7Fa2g0Qr44=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13zsm6rjnrqmpqnhjxkl6ykcmwpffnua825n6w35k5vzgxvu528qmj9anj29xsxmljw5t2465q5ax6g83k664t9e8exlm4ekv56ztqytggu9fyt5ja9jvj7z8ac94zccm0x72xcpvfs3fwwsn84d9q79swsdxk6pm7ayrjvpnedq9l8qge4mevm4gewxke93dcdcsqc7qd7t79f4ku23hja223rwra4h2nw3wk4dnj7fjpdzneanmlak9vg77dr0tr24m8gfxsctcr50ej7lhtq60g2jnpu5040p6ncfvhdxjxjm4gd6uraaangmhpa4zr9vzyajydfqqwe4x2synz303x9zewpqu7ku6twg9dndrjql4r8hkgjfr6su868p8ruytz8s3ryl7fjl0w93r6c7t082ndje8ch5ekfylgqvx7h90jdeg6as9v6mncwt52gjhpfq9u5prc78tvx3zz9ze2af8rxj4hjysgjhrd6q45rwwv0xczktkcwdee6v8p9re427astprhq4v7qxr83zzpgy4333f7ka6mwewpde2rnhzp405hv8dms28qydwzja90sxue6q22vuk2g3ec9sq5jg8d9hzn0uqvc95rwtacgd35xpm3avg9vrgd83x3tywzc2qwy36t4m547wgzz7lq72u3ujj00nmqjq2802lsuj5pqmkz6m0kjcutzlmx59ry8swnwe8jdnmw96fw0uhn0d24n7z6txk0xkf6g4m6rps3xzm3d5e6d0k2frqyh45vhxtghcnwe9yqrzhzqctjnuqwaksqzy6kf27vwcfqjqx50e6fx62r4p9chkpwk8usurpngrx9svh946fgygssk2dvka04hek8rmh4lavcuctxe9582fe3hnkpjc63vkgsanhvwwjyjt6672yvqwrzcqnz0wcqxqpje7wwzqpfg8nxeuaqx0ysxhgywuw5xpef4ej3svn8qjhu6r97eucdqarhhe5ws2js25rm2xrj7xfl9sjm98uzz68dvuemjjxl9g6nm39dhmmdtwwj4fu2xhhu4yz4ntvj4hmnapcz2dsxfpn4er2yjpuny7ctq9kwh977uze0zngthsuud7nn9w2x2ygg6n55uxp84j3ym25rlg6h2dje22wq539k0uuewg4xalq245pffyh4wz2d9480jgepfe6sqvjudt75a2ggnrc558ussyhznusk2qyeq97c5y59jq4j2rg2yull97p08yjrf7vd6fk8q9epxwa6vq3k6ajxfp8gzaptcc3gdvsmxeuj73d7c2f3xrke02hz42uh3clxeeryuu253jeqh4fjf923290lf2q045x6k3j9emnnyygfzl3uq3fa9qr8qrmnud0j2zaszg0m6nn7tcmxwtfshdq9whyjrq8y3e9kvvx4tsme4cxvnykxkeapjyndnqq5z0t3clu9tqnvtppgk95n3340w9cnnngfx40u6dz54e8mggxvfwsem838nvdhq7czs3eccgztd34cxq0qvan7p3708pylxj23wjt8x72c2ww7we3z6pyc2evuehcepvwvlk5v52433s7nh386xru3d63grlpckt2r2nfk6jqgkczhna95qjpeyccaxd00fjmus52c79knwqufq7a4qrzucdv89msr9k5qskgjpp34y20ceak77ujxn9zgwptc2y947pmj9etfn7h05vgj4ueqv7zfkjuwhdtg399828qnphjv3vrfgsnf6kq8pzzgr5q48fa6p8l2vsxc2artuukxspm2w339zu62v64e54vt562y9gxwl5wkr84ukpz5qj5kpqzgvsltq6tsvwlz53ald087fk76ej6gkvhv42rxjjcnhns0v2f7ymu74xxj4ydm60dm8ulhekyta8e424tmcyuknzyvjzrd8tvfppxakvsx7q233ww8g7l56av
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T00:51:17Z"
  mac: ENC[AES256_GCM,data:DsyLYURuU78duqOm9rbi3++JeEQHUyEsKxHRf1cWZBvzsxdjgZczBBOI2F0+r55Duq1MR5bsLCas/qP74+oEOkfHWb4NXtX1tXHPXwvMeLA8SZ7qB2b6HnOAQd5TeFRLHUDI9/VgEHdnq1eVXrHMPrjl7XSBSyskV4/sHxofmA8=,iv:VLGPZsbm5wQwRBT1ZMGTECIE+7dhVIl5niZPLcYM378=,tag:EkUXLiQ4sQBf0SwAboK9OA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
