apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:u9/MylyrFVJQKVU/0FX4TbrDCdNe+UElUmkegdZaMenDk81sXEeSJImp7bZ9KOlwUAb2ZC8=,iv:HKEoCtqI5dwmEtqge0Ze+xBKcseFLBEi2AoOZ1hZDW4=,tag:Khe224v83MG4lvqXLyktJg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDI5Zmh6eExF
        aGxYN2Q3T255ZzJ0VXFNWXBLTmZCendoa2VVV3k5ckw2Qzh3cS94NnArektVSU50
        NmRVY2FNZTFjVlVYTjRBbjY3ODJ1c21QcEJ6R2NtTGJkdGxIVUM1ZWxSMWcwUjNW
        S0c1cWxqdmtuRklEUGJ5SEZoQmVsZVhWdEIrREY0cDlRbHJSSktxbEwrQlhMMHRW
        SERweDFSb0NGNGY1UktINndGOFNrdmlvSUZOQ0p0MTJEMFV1RHl6NkpIcWtkTkcx
        TSs3UU1oY0Y3QVRhU01lWi95dXFGVkcwMmZCNGIvOVZkQWd1K0R0Z2JVbVVpdkk2
        Y3R1S1JuNFVEMWE4eC9nVTArQU55Szd1RWVsY2EzOHBhVXovUStzSVI4SCtHbTZp
        SGdOdWg4QjZOSzIyYlFmaTVLVTZ2MFdoOEN6WldHU3E4V25IajZTMzFiYjh0eS96
        Z1hSSmxVWVdjSFNteHlIWTZDTTZZVXFKUDJOTmFaMXRiTjlKc2VLNUxCTjNYWjdo
        WU5zdkpZVjI5UXJUNXUvZldzNlRHajdPamxBTXpmNnNxQWZiQWFCN1QzT1ZwdmdV
        WWVGTEcxT2dFbUZpUXdVMHdtVDc1YmFYU1MrSVZOR2k1SHlFYXFVWDVQVnNzcVc1
        YVAwcTJwV3FHV1c4MjV3dVFTVk1VNmZiTTJLMFIzdTVrUTUydTdaeU9EODhnOVA4
        RVhzN2c4QS9WbHRXRmZVK2dzTTVqOE80MWcrZEwzQ3hIKytaMXM4aHp3cGxlbE5H
        aDhkL05oZWRBZXZxaVVxZGZaVHBTOEJZRHIyMGJLNEFRa0NpSVlpckZjcFFXRllz
        Rk9iV0d4V0g0a0VVVFhwNXlqb1Zzc01OeXhxZVhkUURwNWtqQ1FGY1JXOUIxdXEy
        aU1FRXZnVWFTVWJHMHJWQTFISTFpYWpQM1lEb2crSGlPeG9rZVVuR2FhRVdGMDZh
        LzJ5Q2JRempJMGhNclJraGZpcXBSVHdpazZCOTJpR3J2aUI4SXRqeHJGWjhrbFNp
        T0FHMGVPTk1vQW5hSVgrMUk4RUdKOXJKSFFObWg2dk5rREF0QzVrdGpVNHczTDlY
        R3FUckRPdTUvREpKT1BMVjRTRW1EV0RHeDM3bjlzR2l0UEVITDZoSUZHa2ZieFZX
        YU1HV0ZnNjJLUjJRcERGSDZ4ZU9zWVcxTit6UXFMVjFTdXI3VDRnUmdodzJGbS9D
        bXBuVlBQVHpEYm52dHlVTTdKUDc3NnpvdVJTQXZxZFg3YVAxY3FqSUlpbWZjVUNX
        SHNRNGZmK1VPTXlSY1ZtTTVUcTdrZm5CRzZZdVFObnM3WW1OTVJEOWhOWTh6bURO
        eUwrZ3BJTjRLem0wNVdCMEllczNuRk8wUW1Bem5XbGs5b0d2NlRyOWJweFNaUW1x
        MmJEemlyUldmeFovVGFGNmUxTGlpRzVvRUlMdDFBM0taaUhSMHFTdUdjWloycmNE
        eTkwaTFQQ2xKeHlVbXZNakowSkNQNzZmTjZHNnBCdUhwMFlGK0p4TENOUzl6WWNr
        N1k4WDVMbER3QzRNWlRyODBJTHB3aEpWeGtvdko1aW50OWJqNVlBTWZ1dTZHSE5y
        L01vQnN1NVUvcW14QWVreHlkTXVsblM5OGRZaWQ3a1dYLy9aUExFMGUzR29NRVFx
        VTBkNzBKNkRvK0Q3emRuWXozZm0vZzVyUjcxYXdTejVlb0xXQTJ1YVJmZ1JzWUZy
        anEwY1ZTSVZZQVR3TFBVU2U5dVpJdThpbzN5MkNkU1BsUGxNZDJyZWh1ODNoa2Fj
        OHoyUElzQWlaWmRHVjd5L3ZqYWdYRTE4aWNncHF2S0pHU2RSeFpYTlQwRTBKOW11
        NDdwWUhHVzNNb0xIZWVQN1FCYjF3Z1NpM1V2VzltTHZMTTRab1FzU1ZDTFZnZ2pO
        amxGQVQzdnJXampWTGJ6djl0UkNaSWVUK1lSTUFQUExTZjVxMEUvTXg4bTlFQQpj
        UEVLZXZvVTR5SnprR3ZCU3FndHBzOC9lbFNJU1lRTzB5UytpT3NoVXhvCi0tLSBW
        aHhKNmc5V0FVVUh2YkJFQlV5UU45WXdEaHgrTXR0UHIrcGZYNG1qbzd3CmjA56MU
        LxQPgnzaIhjljk/Ma0IaWlNG8qb/5ZH55jliouJx27d53W+gRWR9kwUbN8eXXrK8
        3TLZYDdAI/rI9Dc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13zsm6rjnrqmpqnhjxkl6ykcmwpffnua825n6w35k5vzgxvu528qmj9anj29xsxmljw5t2465q5ax6g83k664t9e8exlm4ekv56ztqytggu9fyt5ja9jvj7z8ac94zccm0x72xcpvfs3fwwsn84d9q79swsdxk6pm7ayrjvpnedq9l8qge4mevm4gewxke93dcdcsqc7qd7t79f4ku23hja223rwra4h2nw3wk4dnj7fjpdzneanmlak9vg77dr0tr24m8gfxsctcr50ej7lhtq60g2jnpu5040p6ncfvhdxjxjm4gd6uraaangmhpa4zr9vzyajydfqqwe4x2synz303x9zewpqu7ku6twg9dndrjql4r8hkgjfr6su868p8ruytz8s3ryl7fjl0w93r6c7t082ndje8ch5ekfylgqvx7h90jdeg6as9v6mncwt52gjhpfq9u5prc78tvx3zz9ze2af8rxj4hjysgjhrd6q45rwwv0xczktkcwdee6v8p9re427astprhq4v7qxr83zzpgy4333f7ka6mwewpde2rnhzp405hv8dms28qydwzja90sxue6q22vuk2g3ec9sq5jg8d9hzn0uqvc95rwtacgd35xpm3avg9vrgd83x3tywzc2qwy36t4m547wgzz7lq72u3ujj00nmqjq2802lsuj5pqmkz6m0kjcutzlmx59ry8swnwe8jdnmw96fw0uhn0d24n7z6txk0xkf6g4m6rps3xzm3d5e6d0k2frqyh45vhxtghcnwe9yqrzhzqctjnuqwaksqzy6kf27vwcfqjqx50e6fx62r4p9chkpwk8usurpngrx9svh946fgygssk2dvka04hek8rmh4lavcuctxe9582fe3hnkpjc63vkgsanhvwwjyjt6672yvqwrzcqnz0wcqxqpje7wwzqpfg8nxeuaqx0ysxhgywuw5xpef4ej3svn8qjhu6r97eucdqarhhe5ws2js25rm2xrj7xfl9sjm98uzz68dvuemjjxl9g6nm39dhmmdtwwj4fu2xhhu4yz4ntvj4hmnapcz2dsxfpn4er2yjpuny7ctq9kwh977uze0zngthsuud7nn9w2x2ygg6n55uxp84j3ym25rlg6h2dje22wq539k0uuewg4xalq245pffyh4wz2d9480jgepfe6sqvjudt75a2ggnrc558ussyhznusk2qyeq97c5y59jq4j2rg2yull97p08yjrf7vd6fk8q9epxwa6vq3k6ajxfp8gzaptcc3gdvsmxeuj73d7c2f3xrke02hz42uh3clxeeryuu253jeqh4fjf923290lf2q045x6k3j9emnnyygfzl3uq3fa9qr8qrmnud0j2zaszg0m6nn7tcmxwtfshdq9whyjrq8y3e9kvvx4tsme4cxvnykxkeapjyndnqq5z0t3clu9tqnvtppgk95n3340w9cnnngfx40u6dz54e8mggxvfwsem838nvdhq7czs3eccgztd34cxq0qvan7p3708pylxj23wjt8x72c2ww7we3z6pyc2evuehcepvwvlk5v52433s7nh386xru3d63grlpckt2r2nfk6jqgkczhna95qjpeyccaxd00fjmus52c79knwqufq7a4qrzucdv89msr9k5qskgjpp34y20ceak77ujxn9zgwptc2y947pmj9etfn7h05vgj4ueqv7zfkjuwhdtg399828qnphjv3vrfgsnf6kq8pzzgr5q48fa6p8l2vsxc2artuukxspm2w339zu62v64e54vt562y9gxwl5wkr84ukpz5qj5kpqzgvsltq6tsvwlz53ald087fk76ej6gkvhv42rxjjcnhns0v2f7ymu74xxj4ydm60dm8ulhekyta8e424tmcyuknzyvjzrd8tvfppxakvsx7q233ww8g7l56av
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T18:38:02Z"
  mac: ENC[AES256_GCM,data:T164nEXGhUspsSV/Fa2ty2u9KSYTuKl8d2NI66fOq7R9bHFDODJ/fV04LPFvfqlcFwce9nO92AS9nwOLzN3mDBXiCi+G8i+MSfvV4MsI9TJzbSgtisVDxbS3Y/NALOnAMCH7mHt0pFtuu1CmrAn7maa24mQ2ipvEbOW5aK13cKw=,iv:JEB192e+3klVuZ7FO3WcCEr/PmzZPuQYzsan8UlkCHs=,tag:NqbxmPu3OH394QhOUbUnLg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
