apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:EtHj9USFCEnczfU8LucsvX1Q96OsL/AOw7XqVDm7vhCwXO5sMwixJM9h7wf3tCyR1ZlKstA=,iv:911clzI0X2a7poy3S+lMlYOisYvp6T2/DcZS0fEt1A0=,tag:PPP88nB6UHZgjYSk3wH6dA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFltYzdoYU9u
        SU5xQ1VtT0h2YkQvTW8ycFVQQ2drN2dtSGZNc0RSUjFHSDFIWU5BdDdiSExVaC9L
        dXJ3K2RpbmM3NkFucnk0c3dKWWs1NkxERVdFN0x0K1NhcmdIU3VFdWRJa1ZqbFZF
        UlNiVEozVGcrZHZ3cWdZdFVKSmxlUitRUVpRbXlES1hVaFJnUjkzV2ZpVTFqK3Mz
        emtCM1FHTnlzZ0dQOHlKS0wzajh5dEk2ZllaUVJ2d2RTN0FraTNQTXlhZzR4cndG
        QkljRXlqb1psWFJweWc5cU92MlpwQXZDN1hnNVBNaGNYamxFTEFlZEgwTHRVeSsw
        R1RhK3hha0tTSm4rMkFiOTF6WWtqVUkrbjZtR250MnBxUGcxNGFiUjdSaUl5RGNS
        Uy9XOTlXS0kreTNWOWN6Q0lDajZ6b3lvMnhMMlJZeDRIbE51K3AwcFVNbHNFSWV4
        NlkyL3FFRHFQMzE2blMzZ2p5NWVoTE9Dck1yd002dDdvUEEvTU5FWm1EL2dtUW1v
        RDg3NUVWSkh3eUtGbXJJT0FsaGtPMEt2bURJcFJveDdsQ3JETXUwODZEN1ZtdGo2
        NHVxMkE1QVRmRHdSY1BFWXlhTnh3bDB4S0drSVhzc2xNalM2RkVHb1JHZENsTGNK
        d1NFRnRwYllqVmhVYStiT2lFL201a1kxTE9KUys3b2swSy9HRTRRMHZDbkl6RTRu
        cW9RTEdHcTl1QktQOHJpZnNqRldMaEx3S0NYcFhkSWRaZU1QaTZSK2ZvUFJmNnZv
        WWJncEg0QUxTdG92SlNMK3BRbHc2N1NHNkJuR1ZtWWZnYWdkS04xckVjZ3RNYWtL
        VUIzQmVid0pFTlZDRVR3YXkwOFB2djJBVTZBY2tZOHE5SjZwRzNVZHFyNGxlNWNV
        TkxQY3ljOUIwQ1I2ZTU3a3dCeVBmTVBYNDNLVG1yRE15M1FhMklLUXBhSXZJZWR5
        QXVZUjU4QWl4dFZzWktwNW8xU284Ri9jQnYwN1hpMTQ3RUFMcXBKbTFKM3BZd29M
        WGhFclZFUkxwNEc0T2dXSFlZb1d1ZFQ3SHNWdEJ6NXhibUdDNVJMS0NXSm9zb2VG
        SDB6dDQzeUNvY0w1SW5FNS9hQW1rdkFNcm1yVmpzVXFxcGdBUFZCMG9MbXNNN3Ev
        VzJ2bXhHWWZFNkFKNENIRFhLTFYyalQ0eFJ6V0ZpMEtuMWZES2VnZk1YVzl5c0Nt
        RVUxNEp6NW5CNkpvcGVyeDhEdE5hS0lZeTduZ3poK1EwLy95V2FsNWllaC9GbENt
        dTA3SkZvQ1ZCYVl6VFVLWDBWWXhvRjlXYW41SHNkRDFEM3ZPZGFheDlwOUN1RGph
        aWFoLzliem1VekpNOVNWT0tQd1ppKys2R3FlMCthZDR6dDBiMFY5eDhVTXFvNDJk
        cUZHSWZpeHovMkZmUUNoNzhncitsMEwxVVBrRFgrWjRHNXQxSGdmcmswWE1JbGlw
        c0NvdXBMRFdEeTNhV2Fhek4rNnMyUmpzNXI0UkVBV0cwTm9JREtKT0Nlc0N4OFNz
        c0RnZ0dOWUxLM3M0a3pmMXU5bm1ndWZMbURsWXhkbFVLbWZrSEZkZEcvaEcvbDl2
        SkxKbjJRY0JlQm9EQXl6amhBK3UvTTArTVNHT29CNTBZSWh4TXZFOWM2VVhNUThV
        UHJrQ2Y5SGdnUW9YSFB3VnZwNFRtR1RCcVBzcGRadGNzVDRHbE1vOWp6UWt0d1FO
        eHpPSG9wbnNMditvTUhxRkV3RjlLWjZkb2ladWFVWUpNcm96cXZidWJRYmxzU3Ax
        eFZRSnNFM3V1UktRSVpmT3dHVEhNeVlKaVVUMGhIV2srZW1tMlBQa0haTTJGNGYr
        UjJGNXVaYndEM21nZ3dveDBiOHVYNVdEbVkwcUNUdnNVTUFNOEsyYU9raVluNHpk
        OG1zMDZSTFpOblkyZTY1b2RRQXVoVUR5eSszSTBNb2V5eHV0cDFldTJtNWxmQQpR
        YUw0MS92YlRDNTg0b29hYmZKa1BsZytSR2trMnR4Rmt5cHlLalREZmpRCi0tLSBN
        aVo5YlNWWlU5d2NxUEtZby9meVVLaWdmYlNMT2hPbjRMcStxYWxIRHU0CsRpn+X0
        AaQZJ8ZZCZFZDZub4DUOzcOhm3OCHhIJStWwt1Uwq6A9v7gb1jR5ugjjDRwTBC2I
        /QAcPx02s3PUZF8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13zsm6rjnrqmpqnhjxkl6ykcmwpffnua825n6w35k5vzgxvu528qmj9anj29xsxmljw5t2465q5ax6g83k664t9e8exlm4ekv56ztqytggu9fyt5ja9jvj7z8ac94zccm0x72xcpvfs3fwwsn84d9q79swsdxk6pm7ayrjvpnedq9l8qge4mevm4gewxke93dcdcsqc7qd7t79f4ku23hja223rwra4h2nw3wk4dnj7fjpdzneanmlak9vg77dr0tr24m8gfxsctcr50ej7lhtq60g2jnpu5040p6ncfvhdxjxjm4gd6uraaangmhpa4zr9vzyajydfqqwe4x2synz303x9zewpqu7ku6twg9dndrjql4r8hkgjfr6su868p8ruytz8s3ryl7fjl0w93r6c7t082ndje8ch5ekfylgqvx7h90jdeg6as9v6mncwt52gjhpfq9u5prc78tvx3zz9ze2af8rxj4hjysgjhrd6q45rwwv0xczktkcwdee6v8p9re427astprhq4v7qxr83zzpgy4333f7ka6mwewpde2rnhzp405hv8dms28qydwzja90sxue6q22vuk2g3ec9sq5jg8d9hzn0uqvc95rwtacgd35xpm3avg9vrgd83x3tywzc2qwy36t4m547wgzz7lq72u3ujj00nmqjq2802lsuj5pqmkz6m0kjcutzlmx59ry8swnwe8jdnmw96fw0uhn0d24n7z6txk0xkf6g4m6rps3xzm3d5e6d0k2frqyh45vhxtghcnwe9yqrzhzqctjnuqwaksqzy6kf27vwcfqjqx50e6fx62r4p9chkpwk8usurpngrx9svh946fgygssk2dvka04hek8rmh4lavcuctxe9582fe3hnkpjc63vkgsanhvwwjyjt6672yvqwrzcqnz0wcqxqpje7wwzqpfg8nxeuaqx0ysxhgywuw5xpef4ej3svn8qjhu6r97eucdqarhhe5ws2js25rm2xrj7xfl9sjm98uzz68dvuemjjxl9g6nm39dhmmdtwwj4fu2xhhu4yz4ntvj4hmnapcz2dsxfpn4er2yjpuny7ctq9kwh977uze0zngthsuud7nn9w2x2ygg6n55uxp84j3ym25rlg6h2dje22wq539k0uuewg4xalq245pffyh4wz2d9480jgepfe6sqvjudt75a2ggnrc558ussyhznusk2qyeq97c5y59jq4j2rg2yull97p08yjrf7vd6fk8q9epxwa6vq3k6ajxfp8gzaptcc3gdvsmxeuj73d7c2f3xrke02hz42uh3clxeeryuu253jeqh4fjf923290lf2q045x6k3j9emnnyygfzl3uq3fa9qr8qrmnud0j2zaszg0m6nn7tcmxwtfshdq9whyjrq8y3e9kvvx4tsme4cxvnykxkeapjyndnqq5z0t3clu9tqnvtppgk95n3340w9cnnngfx40u6dz54e8mggxvfwsem838nvdhq7czs3eccgztd34cxq0qvan7p3708pylxj23wjt8x72c2ww7we3z6pyc2evuehcepvwvlk5v52433s7nh386xru3d63grlpckt2r2nfk6jqgkczhna95qjpeyccaxd00fjmus52c79knwqufq7a4qrzucdv89msr9k5qskgjpp34y20ceak77ujxn9zgwptc2y947pmj9etfn7h05vgj4ueqv7zfkjuwhdtg399828qnphjv3vrfgsnf6kq8pzzgr5q48fa6p8l2vsxc2artuukxspm2w339zu62v64e54vt562y9gxwl5wkr84ukpz5qj5kpqzgvsltq6tsvwlz53ald087fk76ej6gkvhv42rxjjcnhns0v2f7ymu74xxj4ydm60dm8ulhekyta8e424tmcyuknzyvjzrd8tvfppxakvsx7q233ww8g7l56av
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T18:47:23Z"
  mac: ENC[AES256_GCM,data:tJsF8BLMh1wQ1nOEKPWjCeowstKY3oW6GScgFixbqjwKq2FgSPe8vOGn9y77vlQ3WIvs/NToa/jApQOoIf0jVq0RDZ9L0UnxwXSqGcnze8tjYnbFDm6QIoJxFh+xj76SqgR0E9nJyLiDppSKvz2nLdlh4BQvMzaQ+N8FIsIHGzg=,iv:30WWvxMqhbNkQngo7sbME/EfB+o2P983fM6Frb+VwIA=,tag:Y6i7mXnWX1Z5bExoUe45dQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
